deploy:
  id: <%= ENV["HATCHBOX_RELEASE"] %>
  git_sha: <%= ENV["HATCHBOX_REVISION"] %>
  # The deploy description is optional.
  description: "Deployed <%= ENV["HATCHBOX_REVISION"] %> on <%= Rails.env %>"
