# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke', movie: movies.first)

AppraisalType.create(name: "Payment Receipt', updated_by: "brita")
AppraisalType.create(name: "Comparable Value (like or comaparble item)', updated_by: "brita")
AppraisalType.create(name: "External Appraisal - outside vendor', updated_by: "brita")
AppraisalType.create(name: "Other', updated_by: "brita")

Department.create!([
  {name: 'American Culture', dept_number: 193000, short_name: 'Am Cult', updated_by: "brita"},
  {name: 'Anthro-History', dept_number: 179200, short_name: 'Anthro-Hist', updated_by: "brita"},
  {name: 'Anthropology', dept_number: 193000, short_name: 'Cult', updated_by: "brita"},
  {name: 'Applied Physics', dept_number: 184600, short_name: 'AppPhys', updated_by: "brita"},
  {name: 'Asian Languages & Cultures', dept_number: 176000, short_name: 'Asian', updated_by: "brita"},
  {name: 'Astronomy', dept_number: 172500, short_name: 'ASTR', updated_by: "brita"},
  {name: 'Biological Station', dept_number: 172700, short_name: 'UMBS', updated_by: "brita"},
  {name: 'Biological Station: Osborn', dept_number: 206610, short_name: 'UMBS-Osborn', updated_by: "brita"},
  {name: 'Biology - Undergraduate', dept_number: 188900, short_name: 'BIO', updated_by: "brita"},
  {name: 'Biophysics', dept_number: 554000, short_name: 'BIOP', updated_by: "brita"},
  {name: 'Botanical Gardens', dept_number: 206000, short_name: '-', updated_by: "brita"},
  {name: 'CAAS: S. African Init.', dept_number: 550100, short_name: '-', updated_by: "brita"},
  {name: 'CaMLA: AEE', dept_number: 193000, short_name: '-', updated_by: "brita"},
  {name: 'CaMLA: Consulting', dept_number: 181780, short_name: '-', updated_by: "brita"},
  {name: 'CaMLA: ECCE (B2)', dept_number: 181740, short_name: '-', updated_by: "brita"},
  {name: 'CaMLA: ECPE (C2)', dept_number: 181750, short_name: '-', updated_by: "brita"},
  {name: 'CaMLA: General Admin', dept_number: 181700, short_name: '-', updated_by: "brita"},
  {name: 'CaMLA: GSI-OET', dept_number: 181760, short_name: '-', updated_by: "brita"},
  {name: 'CaMLA: MELAB', dept_number: 181710, short_name: '-', updated_by: "brita"},
  {name: 'CaMLA: MET', dept_number: 181720, short_name: '-', updated_by: "brita"},
  {name: 'CAMLA: Practice Materials', dept_number: 181790, short_name: '-', updated_by: "brita"},
  {name: 'CaMLA: Test Publications', dept_number: 181730, short_name: '-', updated_by: "brita"},
  {name: 'CAMLA: Young Learners', dept_number: 181800, short_name: '-', updated_by: "brita"},
  {name: 'Chemistry', dept_number: 173500, short_name: 'CHEM', updated_by: "brita"},
  {name: 'Classical Art/Archaeology', dept_number: 173700, short_name: 'Art/Arch', updated_by: "brita"},
  {name: 'Classical Studies', dept_number: 174000, short_name: 'ClasStds', updated_by: "brita"},
  {name: 'Cognitive Neuroscience Program', dept_number: 550500, short_name: '-', updated_by: "brita"},
  {name: 'Cognitive Sci&Mach Intel', dept_number: 174800, short_name: '-', updated_by: "brita"},
  {name: 'College of Lit, Science & Arts', dept_number: 170000, short_name: 'DEAN', updated_by: "brita"},
  {name: 'Communication Studies', dept_number: 188300, short_name: 'COMM', updated_by: "brita"},
  {name: 'Comparative Literature', dept_number: 191400, short_name: 'Comp Lit', updated_by: "brita"},
  {name: 'Complex Systems', dept_number: 550400, short_name: 'CSCS', updated_by: "brita"},
  {name: 'Computer Science', dept_number: 174600, short_name: '-', updated_by: "brita"},
  {name: 'Culture and Cognition Program', dept_number: 550300, short_name: '-', updated_by: "brita"},
  {name: 'DAAS', dept_number: 190300, short_name: 'DAAS', updated_by: "brita"},
  {name: 'Dean: Academic Affairs', dept_number: 170300, short_name: '-', updated_by: "brita"},
  {name: 'Dean: Auxiliary Services', dept_number: 170700, short_name: '-', updated_by: "brita"},
  {name: 'Dean: Classrooms', dept_number: 171000, short_name: 'Classrooms', updated_by: "brita"},
  {name: 'Dean: Deans Office', dept_number: 174200, short_name: 'LSA Dean', updated_by: "brita"},
  {name: 'Dean: Development', dept_number: 170200, short_name: 'ADV', updated_by: "brita"},
  {name: 'Dean: East Hall Tech Svcs', dept_number: 185600, short_name: '-', updated_by: "brita"},
  {name: 'Dean: Facilities', dept_number: 170110, short_name: 'FCL', updated_by: "brita"},
  {name: 'Dean: Facilities - USB', dept_number: 171250, short_name: '-', updated_by: "brita"},
  {name: 'Dean: Facilities Projects', dept_number: 170100, short_name: 'Facilities', updated_by: "brita"},
  {name: 'Dean: Finance', dept_number: 170500, short_name: 'Finance', updated_by: "brita"},
  {name: 'Dean: Human Resources', dept_number: 173800, short_name: 'HR', updated_by: "brita"},
  {name: 'Dean: Info. Technology', dept_number: 172900, short_name: 'TS', updated_by: "brita"},
  {name: 'Dean: Instruc Support Svcs', dept_number: 171200, short_name: 'TSAT', updated_by: "brita"},
  {name: 'Dean: Interdept Activity', dept_number: 179900, short_name: '-', updated_by: "brita"},
  {name: 'Dean: Invested Department', dept_number: 173600, short_name: '-', updated_by: "brita"},
  {name: 'Dean: Machine Shop', dept_number: 170150, short_name: '-', updated_by: "brita"},
  {name: 'Dean: Mgmt. Info. Systems', dept_number: 173900, short_name: '-', updated_by: "brita"},
  {name: 'Dean: Outreach Staffing', dept_number: 174100, short_name: '-', updated_by: "brita"},
  {name: 'Dean: Planning/Operations', dept_number: 174400, short_name: '-', updated_by: "brita"},
  {name: 'Dean: Research/Grad. Stud.', dept_number: 174300, short_name: '-', updated_by: "brita"},
  {name: 'Dean: Shared Services', dept_number: 174250, short_name: '-', updated_by: "brita"},
  {name: 'Dean: Shared Svc-Dennison', dept_number: 174253, short_name: '-', updated_by: "brita"},
  {name: 'Dean: Shared Svc-MLB-Thayr', dept_number: 174251, short_name: 'HUM', updated_by: "brita"},
  {name: 'Dean: Shared Svc-West Hall', dept_number: 174252, short_name: 'Fin WH', updated_by: "brita"},
  {name: 'Dean: ShSvc-South State St', dept_number: 174255, short_name: 'SocSci', updated_by: "brita"},
  {name: 'Dean: Software Recharge', dept_number: 172950, short_name: '-', updated_by: "brita"},
  {name: 'Dean: TA Training', dept_number: 171600, short_name: '-', updated_by: "brita"},
  {name: 'Dean: Undergrad. Education', dept_number: 171300, short_name: 'UgradED', updated_by: "brita"},
  {name: 'Earth & Env Sci: CampDavis', dept_number: 177075, short_name: 'EES-CampDavis', updated_by: "brita"},
  {name: 'Earth & Env Sci: CC', dept_number: 177050, short_name: '-', updated_by: "brita"},
  {name: 'Earth & Env Sci: EMAL', dept_number: 177100, short_name: '-', updated_by: "brita"},
  {name: 'Earth & Environmental Sci.', dept_number: 177000, short_name: 'EARTH', updated_by: "brita"},
  {name: 'Ecology & Evolutionary Bio', dept_number: 189100, short_name: 'EEB', updated_by: "brita"},
  {name: 'Economics', dept_number: 175000, short_name: 'ECON', updated_by: "brita"},
  {name: 'ELI Testing and Cert Div', dept_number: 181501, short_name: '-', updated_by: "brita"},
  {name: 'ELI Testing and Cert Div', dept_number: 181600, short_name: '-', updated_by: "brita"},
  {name: 'English Language & Lit.', dept_number: 175500, short_name: 'ENG', updated_by: "brita"},
  {name: 'English Language Institute', dept_number: 181500, short_name: 'ELI', updated_by: "brita"},
  {name: 'Germanic Languages & Lit.', dept_number: 178000, short_name: 'German', updated_by: "brita"},
  {name: 'GIEU Program', dept_number: 517250, short_name: '-', updated_by: "brita"},
  {name: 'Greek & Roman History Pgm', dept_number: 174010, short_name: 'Greek&Roman', updated_by: "brita"},
  {name: 'Herbarium', dept_number: 201200, short_name: 'Herb', updated_by: "brita"},
  {name: 'History', dept_number: 179000, short_name: 'Hist', updated_by: "brita"},
  {name: 'History of Art', dept_number: 179500, short_name: 'HART', updated_by: "brita"},
  {name: 'Humanities Departments', dept_number: 173000, short_name: '-', updated_by: "brita"},
  {name: 'Humanities Institute', dept_number: 171100, short_name: 'Hum Inst', updated_by: "brita"},
  {name: 'Humanities Collaboratory', dept_number: 173100, short_name: 'MI Hum Collab', updated_by: "brita"},
  {name: 'II: African Studies Center', dept_number: 195400, short_name: 'II-ASC', updated_by: "brita"},
  {name: 'II: Armenian Studies', dept_number: 195200, short_name: 'II-ASP', updated_by: "brita"},
  {name: 'II: Atlantic Studies Init.', dept_number: 191800, short_name: '-', updated_by: "brita"},
  {name: 'II: Chinese Studies', dept_number: 191000, short_name: 'II-LRCCS', updated_by: "brita"},
  {name: 'II: CSST', dept_number: 195300, short_name: '-', updated_by: "brita"},
  {name: 'II: European Studies', dept_number: 195000, short_name: 'II-CES', updated_by: "brita"},
  {name: 'II: Human Rights Initiatve', dept_number: 194200, short_name: 'II-DHRC', updated_by: "brita"},
  {name: 'II: Islamic Studies Prog', dept_number: 192600, short_name: 'II-GISC', updated_by: "brita"},
  {name: 'II: Japanese Studies', dept_number: 192000, short_name: 'II-CJS', updated_by: "brita"},
  {name: 'II: Latin Amer & Carib St', dept_number: 195100, short_name: 'II-LACS', updated_by: "brita"},
  {name: 'II: ME & N. African St', dept_number: 192500, short_name: 'II-CMENAS', updated_by: "brita"},
  {name: 'II: Nam Ctr Korean Studies', dept_number: 194300, short_name: 'II-NCKS', updated_by: "brita"},
  {name: 'II: Polish Studies', dept_number: 194100, short_name: 'II-CPPS', updated_by: "brita"},
  {name: 'II: Prg Intl Comp Studies', dept_number: 193700, short_name: 'II-PICS', updated_by: "brita"},
  {name: 'II: Russ, EE & Eurasian St', dept_number: 194000, short_name: 'II-CREES', updated_by: "brita"},
  {name: 'II: S. Asian Studies', dept_number: 194400, short_name: 'II-CSAS', updated_by: "brita"},
  {name: 'II: SE Asian Studies', dept_number: 194500, short_name: 'II-CSEAS', updated_by: "brita"},
  {name: 'II: Weiser Emerging Democ', dept_number: 195500, short_name: 'II-WCEE', updated_by: "brita"},
  {name: 'II: Weiser Europe/Eurasia', dept_number: 195600, short_name: 'II-WCED', updated_by: "brita"},
  {name: 'II: World Performance St', dept_number: 193500, short_name: 'II-WPS', updated_by: "brita"},
  {name: 'International Institute', dept_number: 190000, short_name: 'II', updated_by: "brita"},
  {name: 'Judaic Studies', dept_number: 179100, short_name: 'JUDAIC', updated_by: "brita"},
  {name: 'Kelsey Museum/Archaeology', dept_number: 201500, short_name: 'KELSEY', updated_by: "brita"},
  {name: 'Linguistics', dept_number: 181200, short_name: 'LING', updated_by: "brita"},
  {name: 'LS&A Asia-American Studies', dept_number: 193100, short_name: '-', updated_by: "brita"},
  {name: 'LS&A Coll Inst/Values&Sciences', dept_number: 170900, short_name: '-', updated_by: "brita"},
  {name: 'LS&A Comm on Comp/Historic Res', dept_number: 175100, short_name: '-', updated_by: "brita"},
  {name: 'LS&A Ctr Great Lakes & Aquatic', dept_number: 206600, short_name: '-', updated_by: "brita"},
  {name: 'LS&A Environment Learning Comm', dept_number: 173350, short_name: '-', updated_by: "brita"},
  {name: 'LS&A Inteflex', dept_number: 171800, short_name: '-', updated_by: "brita"},
  {name: 'LS&A Latino Studies', dept_number: 193200, short_name: 'DSI', updated_by: "brita"},
  {name: 'LS&A Mathematical Reviews', dept_number: 206500, short_name: '-', updated_by: "brita"},
  {name: 'LS&A Observatories', dept_number: 172600, short_name: '-', updated_by: "brita"},
  {name: 'LS&A Pgm in Amer. Institutions', dept_number: 170600, short_name: '-', updated_by: "brita"},
  {name: 'LS&A Research Sem Quan Econ', dept_number: 175200, short_name: '-', updated_by: "brita"},
  {name: 'LSA- ITC Fund Stdnt Tech Fees', dept_number: 171350, short_name: '-', updated_by: "brita"},
  {name: 'Marketing & Communications', dept_number: 174500, short_name: '-', updated_by: "brita"},
  {name: 'Mathematics', dept_number: 183000, short_name: 'MATH', updated_by: "brita"},
  {name: 'Molec./Cell./Develop. Bio', dept_number: 189000, short_name: 'MCDB', updated_by: "brita"},
  {name: 'Museum of Anthro Arch', dept_number: 200500, short_name: 'MANTH', updated_by: "brita"},
  {name: 'Museums', dept_number: 200000, short_name: '-', updated_by: "brita"},
  {name: 'Natural Science Department', dept_number: 172200, short_name: '-', updated_by: "brita"},
  {name: 'Near Eastern Studies', dept_number: 183500, short_name: 'MES', updated_by: "brita"},
  {name: 'Organizational Studies', dept_number: 174700, short_name: 'OrgStds', updated_by: "brita"},
  {name: 'OS: Barger Leadership Inst', dept_number: 174705, short_name: 'BLI', updated_by: "brita"},
  {name: 'Paleontology Museum', dept_number: 202000, short_name: 'Mus Paleon', updated_by: "brita"},
  {name: 'Philosophy', dept_number: 184000, short_name: 'PHIL', updated_by: "brita"},
  {name: 'Physics', dept_number: 184500, short_name: 'PHYS', updated_by: "brita"},
  {name: 'Physics: Atomic/Molec./Opt', dept_number: 184550, short_name: '-', updated_by: "brita"},
  {name: 'Physics: Condensed Matter', dept_number: 184540, short_name: '-', updated_by: "brita"},
  {name: 'Physics: Focus Center', dept_number: 184560, short_name: '-', updated_by: "brita"},
  {name: 'Physics: High Energy Exper', dept_number: 184510, short_name: '-', updated_by: "brita"},
  {name: 'Physics: High Energy SPIN', dept_number: 184530, short_name: '-', updated_by: "brita"},
  {name: 'Physics: High Energy Theor', dept_number: 184520, short_name: '-', updated_by: "brita"},
  {name: 'Political Science', dept_number: 185000, short_name: 'PoliSci', updated_by: "brita"},
  {name: 'Political Science: MIW', dept_number: 185100, short_name: 'MIW', updated_by: "brita"},
  {name: 'Program in Neuroscience', dept_number: 189050, short_name: 'Neuro', updated_by: "brita"},
  {name: 'Programs & Centers', dept_number: 172300, short_name: '-', updated_by: "brita"},
  {name: 'Psychology', dept_number: 185500, short_name: 'PSYCH', updated_by: "brita"},
  {name: 'Psychology: CSBYC', dept_number: 185510, short_name: 'CSBYC', updated_by: "brita"},
  {name: 'Religious Studies', dept_number: 194700, short_name: '-', updated_by: "brita"},
  {name: 'Romance Languages & Lit.', dept_number: 186500, short_name: 'RLL', updated_by: "brita"},
  {name: 'Science, Tech and Society', dept_number: 191700, short_name: 'Sci,Tech & Soc', updated_by: "brita"},
  {name: 'Screen Arts & Cultures', dept_number: 191600, short_name: 'FTM', updated_by: "brita"},
  {name: 'Slavic Languages & Lit.', dept_number: 187000, short_name: 'Slavic', updated_by: "brita"},
  {name: 'Social Science Departments', dept_number: 172400, short_name: '-', updated_by: "brita"},
  {name: 'Sociology', dept_number: 187500, short_name: 'SOC', updated_by: "brita"},
  {name: 'Statistics', dept_number: 188500, short_name: 'STATS', updated_by: "brita"},
  {name: 'Summer Language Inst.', dept_number: 191300, short_name: 'UG Summer Lang', updated_by: "brita"},
  {name: 'Sweetland Writing Center', dept_number: 175600, short_name: 'Sweetland', updated_by: "brita"},
  {name: 'UG: CGIS', dept_number: 171500, short_name: 'CGIS', updated_by: "brita"},
  {name: 'UG: Comprehensive Studies', dept_number: 191200, short_name: 'CSP', updated_by: "brita"},
  {name: 'UG: Curriculum Support', dept_number: 171900, short_name: '-', updated_by: "brita"},
  {name: 'UG: Environment', dept_number: 173300, short_name: '-', updated_by: "brita"},
  {name: 'UG: Global Scholars Prog', dept_number: 191270, short_name: '-', updated_by: "brita"},
  {name: 'UG: Hlth. Science Scholars', dept_number: 174900, short_name: '-', updated_by: "brita"},
  {name: 'UG: Honors', dept_number: 180000, short_name: 'HONORS', updated_by: "brita"},
  {name: 'UG: IDEA Institute', dept_number: 171390, short_name: '-', updated_by: "brita"},
  {name: 'UG: InterGroup Relations', dept_number: 191250, short_name: '-', updated_by: "brita"},
  {name: 'UG: Language Resource Ctr.', dept_number: 182000, short_name: 'LRC', updated_by: "brita"},
  {name: 'UG: Lloyd Hall Scholars', dept_number: 170400, short_name: 'Lloyd', updated_by: "brita"},
  {name: 'UG: M-SCI Program', dept_number: 172801, short_name: '-', updated_by: "brita"},
  {name: 'UG: Mich Community Schlrs', dept_number: 171700, short_name: '-', updated_by: "brita"},
  {name: 'UG: Mich Research Comm', dept_number: 171401, short_name: '-', updated_by: "brita"},
  {name: 'UG: Museum of Nat History', dept_number: 201000, short_name: 'Mus Nat His', updated_by: "brita"},
  {name: 'UG: Museum Studies Minor', dept_number: 170850, short_name: '-', updated_by: "brita"},
  {name: 'UG: Residential College', dept_number: 186000, short_name: 'RC', updated_by: "brita"},
  {name: 'UG: Science Learning Ctr.', dept_number: 172800, short_name: '-', updated_by: "brita"},
  {name: 'UG: Student Acad. Affairs', dept_number: 170800, short_name: 'Acad Affairs', updated_by: "brita"},
  {name: 'UG: Student Recruitment', dept_number: 173200, short_name: '-', updated_by: "brita"},
  {name: 'UG: University Courses', dept_number: 172100, short_name: '-', updated_by: "brita"},
  {name: 'UG: UROP', dept_number: 171400, short_name: 'UROP', updated_by: "brita"},
  {name: 'Undergraduate Education', dept_number: 171301, short_name: '-', updated_by: "brita"},
  {name: 'Weinberg Inst for Cog Science', dept_number: 181250, short_name: 'Weinberg', updated_by: "brita"},
  {name: 'Womens and Gender Studies', dept_number: 188700, short_name: 'WomStds', updated_by: "brita"},
  {name: 'Zoology Museum', dept_number: 202500, short_name: '-', updated_by: "brita"},
  {name: 'Zoology Museum: ES George', dept_number: 202600, short_name: '-', updated_by: "brita"}
])